### ISSUE TITLE
Doubt regarding omegaConf

### ISSUE THREAD

**Issue by Rohanmunoth** [molecularmodelinglab/bigbind#2]
I am trying to run the analysis.py file. I have installed all the required packages and have installed them using pip. I have created hosts.yaml and cfg.yaml (empty files) in the configs folder. I am getting the following error on running the analysis.py file, 
```
Traceback (most recent call last):
  File "/Users/rohan/Desktop/Koes_lab/New/check/prody_pockets_5A/bigbind-master/analysis.py", line 141, in <module>
    cfg = get_config("local")
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/rohan/Desktop/Koes_lab/New/check/prody_pockets_5A/bigbind-master/utils/cfg_utils.py", line 45, in get_config
    cfg["host"] = hosts[host_name]
                  ~~~~~^^^^^^^^^^^
  File "/Users/rohan/anaconda3/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 375, in __getitem__
    self._format_and_raise(key=key, value=None, cause=e)
  File "/Users/rohan/anaconda3/lib/python3.11/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/Users/rohan/anaconda3/lib/python3.11/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/Users/rohan/anaconda3/lib/python3.11/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohan/anaconda3/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 369, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rohan/anaconda3/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
           ^^^^^^^^^^^^^^^^
  File "/Users/rohan/anaconda3/lib/python3.11/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
            ^^^^^^^^^^^^^^^
  File "/Users/rohan/anaconda3/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 480, in _get_node
    raise ConfigKeyError(f"Missing key {key!s}")
omegaconf.errors.ConfigKeyError: Missing key local
    full_key: local
    object_type=dict
```
How to setup the omegaconf and am I supposed to run the analysis.py or some other file.

**Comment by mixarcid** [comment]
What are you trying to do? Analysis.py just creates some figures I used in the appendix.

The configuration is pretty complicated and we're currently in the process of making a new codebase with a lot simpler config. In the case of analysis.py, I'd recommend removing the get_config() call and changing the line in https://github.com/molecularmodelinglab/bigbind/blob/7c67d75d7f4b0d0f74df5faa62372afc56d34c3d/analysis.py#L73 to point to wherever you downloaded the bigbind set.
